[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _, _
g2 = _, _, _
g3 = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub, r.dom) || g3(r.sub, p.sub)) && r.dom == p.dom && (p.obj == "*" || g2(r.obj, p.obj, r.dom) || keyMatch2(r.obj, p.obj)) && (p.act == "manage" || r.act == p.act)
